language: python
sudo: required
dist: xenial
python: "3.7"

services:
  - docker

before_script:
  - cd python
install:
  - pip install tox
script:
  - tox
  - docker build -t csfulop/lbe-rest-pecan .
  - docker run --rm -p 8080:8080 -d --name lbe-rest-pecan csfulop/lbe-rest-pecan
  - timeout 10 bash -c "while ! curl http://localhost:8080/; do sleep 1; printf .; done"
  - tox -e blackbox
