language: python

services:
  - docker

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
      env: TOXENV=py37

before_script:
  - cd python
install:
  - pip install tox
script:
  - tox
  - docker build -t csfulop/lbe-rest-pecan .
  - docker run --rm -p 8080:8080 -d --name lbe-rest-pecan csfulop/lbe-rest-pecan
  - curl http://localhost:8080/phonebook/
